### ISSUE TITLE
the .exe doesnt even open and then deltes itself

### ISSUE THREAD

**Issue by B1ffot** [Escartem/AmongUsCheatClient#7] opened 2020-10-02 16:21 UTC
exactly what the title says

**Comment by B1ffot** [comment] 2020-10-02 16:49
this is on the beta one

**Comment by Escartem** [comment] 2020-10-02 17:31
Very likely caused by your antivirus

**Comment by B1ffot** [comment] 2020-10-02 18:34
How to fix?

**Comment by B1ffot** [comment] 2020-10-02 18:34
I can’t un quarantine it

**Comment by Escartem** [comment] 2020-10-02 20:12
If it’s windows defender you should be able to authorize it on the computer but I might require admin rights. If you use any other antivirus, just look at their documentation

**Comment by B1ffot** [comment] 2020-10-02 20:18
It’s not that it a anti virus that quarantined it but I can’t Un quarantine it???????????

**Comment by Escartem** [comment] 2020-10-02 21:57
I can’t know what software did this and how to unquarantine the file, look up to some online documentation depending on your computer antivirus

**Comment by B1ffot** [comment] 2020-10-03 06:16
What does that mean?

**Comment by B1ffot** [comment] 2020-10-03 07:04
it is cylance antivirus that is stopping it

**Comment by B1ffot** [comment] 2020-10-03 07:09
will running as admin help? and is it safe to do so

**Comment by B1ffot** [comment] 2020-10-03 07:12
my anti virus doesnt quarintine version 0.0.2 but i need the beta one which is the one thats get quarintined

**Comment by Escartem** [comment] 2020-10-03 10:12
If you have cylance as an antivirus, then look at the docs to know what to do.
[Here is the support](https://www.blackberry.com/us/en/support/smartantivirus), positing an issue here means that the problem is coming from the client but here it comes from cylance so please contact them and ask them before asking here
And also, please update your message instead of posting multiples one

**Comment by B1ffot** [comment] 2020-10-03 11:54
Ok

**Comment by Escartem** [comment] 2020-10-05 07:52
I'm closing this for now. If you need any further help, you can still comment this issue.

**Closed as completed by Escartem** 2020-10-05 07:52 UTC
Labels: bug
