### ISSUE TITLE
Repair doesnt work

### ISSUE THREAD

**Issue by cool-guy123456** [Escartem/AmongUsCheatClient#18] opened 2020-10-14 17:55 UTC
**Please check this before posting an issue**

- [ ] I've made sure my issue isn't related to / fixed by #1
- [ ] I know that some features don't work in the latest beta
- [ ] I'm using the correct version of the client (0.0.2 for the version 2020.9.9s of the game and 0.0.3 for the version 2020.9.22s )
- [ ] I've checked that my antivirus is not causing any of my problem

If you can check all of the following, you can create your issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Game Version: [e.g. v2020.9.22s]
 - Client Version [e.g. 0.0.2]

**Additional context**

**Comment by Escartem** [comment] 2020-10-15 08:14
Duplicate of #11

**Closed as completed by Escartem** 2020-10-15 08:14 UTC
Labels: duplicate
